repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [--fix]
        stages: [pre-commit, pre-merge-commit]
      - id: ruff-format
        stages: [pre-commit, pre-merge-commit]
